// THIS FILE IS AUTOGENERATED BY michcioperz/unholy_mock.py
#![deny(unreachable_patterns)]
#![allow(unused_braces, unused_qualifications)]
#![allow(clippy::absolute_paths)]
#![allow(clippy::too_many_lines, clippy::match_same_arms)]

use crate::common::Address;
use crate::common::utils::MaybeMut;
use crate::engine::{CombRegister, Subcomponent, TickComponent, TickComponentExtra};
use cc2650_constants::AddressExt;
use cmemu_common::HwRegister;

#[derive(Subcomponent, TickComponent, TickComponentExtra)]
#[subcomponent_1to1]
pub struct AutoMockComponent {
    #[flop]
    pub(crate) fcfg1_fcfg1_revision:
        CombRegister<cc2650_constants::FCFG1::FCFG1_REVISION::Register>,

    #[flop]
    pub(crate) fcfg1_icepick_device_id:
        CombRegister<cc2650_constants::FCFG1::ICEPICK_DEVICE_ID::Register>,

    #[flop]
    pub(crate) fcfg1_misc_conf_1: CombRegister<cc2650_constants::FCFG1::MISC_CONF_1::Register>,

    #[flop]
    pub(crate) fcfg1_mac_15_4_0: CombRegister<cc2650_constants::FCFG1::MAC_15_4_0::Register>,

    #[flop]
    pub(crate) fcfg1_mac_15_4_1: CombRegister<cc2650_constants::FCFG1::MAC_15_4_1::Register>,

    #[flop]
    pub(crate) fcfg1_user_id: CombRegister<cc2650_constants::FCFG1::USER_ID::Register>,

    #[flop]
    pub(crate) ccfg_size_and_dis_flags:
        CombRegister<cc2650_constants::CCFG::SIZE_AND_DIS_FLAGS::Register>,

    #[flop]
    pub(crate) ccfg_mode_conf_1: CombRegister<cc2650_constants::CCFG::MODE_CONF_1::Register>,

    #[flop]
    pub(crate) ccfg_mode_conf: CombRegister<cc2650_constants::CCFG::MODE_CONF::Register>,

    #[flop]
    pub(crate) flash_cfg: CombRegister<cc2650_constants::FLASH::CFG::Register>,

    #[flop]
    pub(crate) flash_fpac1: CombRegister<cc2650_constants::FLASH::FPAC1::Register>,

    #[flop]
    pub(crate) aux_wuc_modclken0: CombRegister<cc2650_constants::AUX_WUC::MODCLKEN0::Register>,

    #[flop]
    pub(crate) aux_wuc_modclken1: CombRegister<cc2650_constants::AUX_WUC::MODCLKEN1::Register>,

    #[flop]
    pub(crate) aon_ioc_ioclatch: CombRegister<cc2650_constants::AON_IOC::IOCLATCH::Register>,

    #[flop]
    pub(crate) aon_sysctl_sleepctl: CombRegister<cc2650_constants::AON_SYSCTL::SLEEPCTL::Register>,

    #[flop]
    pub(crate) aon_sysctl_pwrctl: CombRegister<cc2650_constants::AON_SYSCTL::PWRCTL::Register>,

    #[flop]
    pub(crate) aon_sysctl_resetctl: CombRegister<cc2650_constants::AON_SYSCTL::RESETCTL::Register>,

    #[flop]
    pub(crate) aon_batmon_bat: CombRegister<cc2650_constants::AON_BATMON::BAT::Register>,

    #[flop]
    pub(crate) aon_batmon_temp: CombRegister<cc2650_constants::AON_BATMON::TEMP::Register>,

    #[flop]
    pub(crate) fcfg1_ldo_trim: CombRegister<cc2650_constants::FCFG1::LDO_TRIM::Register>,

    #[flop]
    pub(crate) fcfg1_anabypass_value2:
        CombRegister<cc2650_constants::FCFG1::ANABYPASS_VALUE2::Register>,

    #[flop]
    pub(crate) fcfg1_config_osc_top:
        CombRegister<cc2650_constants::FCFG1::CONFIG_OSC_TOP::Register>,

    #[flop]
    pub(crate) fcfg1_ampcomp_th2: CombRegister<cc2650_constants::FCFG1::AMPCOMP_TH2::Register>,

    #[flop]
    pub(crate) fcfg1_ampcomp_th1: CombRegister<cc2650_constants::FCFG1::AMPCOMP_TH1::Register>,

    #[flop]
    pub(crate) fcfg1_ampcomp_ctrl1: CombRegister<cc2650_constants::FCFG1::AMPCOMP_CTRL1::Register>,

    #[flop]
    pub(crate) fcfg1_osc_conf: CombRegister<cc2650_constants::FCFG1::OSC_CONF::Register>,

    #[flop]
    pub(crate) fcfg1_misc_otp_data_1:
        CombRegister<cc2650_constants::FCFG1::MISC_OTP_DATA_1::Register>,

    #[flop]
    pub(crate) fcfg1_trim_cal_revision:
        CombRegister<cc2650_constants::FCFG1::TRIM_CAL_REVISION::Register>,

    #[flop]
    pub(crate) fcfg1_soc_adc_ref_trim_and_offset_ext:
        CombRegister<cc2650_constants::FCFG1::SOC_ADC_REF_TRIM_AND_OFFSET_EXT::Register>,

    #[flop]
    pub(crate) aux_adi4_adc0: CombRegister<cc2650_constants::AUX_ADI4::ADC0::Register>,

    #[flop]
    pub(crate) aon_batmon_flashpumpp0:
        CombRegister<cc2650_constants::AON_BATMON::FLASHPUMPP0::Register>,

    #[flop]
    pub(crate) aux_wuc_pwroffreq: CombRegister<cc2650_constants::AUX_WUC::PWROFFREQ::Register>,

    #[flop]
    pub(crate) aux_wuc_pwrdwnreq: CombRegister<cc2650_constants::AUX_WUC::PWRDWNREQ::Register>,

    #[flop]
    pub(crate) aux_wuc_mcubusctl: CombRegister<cc2650_constants::AUX_WUC::MCUBUSCTL::Register>,

    #[flop]
    pub(crate) ioc_iocfg0: CombRegister<cc2650_constants::IOC::IOCFG0::Register>,

    #[flop]
    pub(crate) ioc_iocfg1: CombRegister<cc2650_constants::IOC::IOCFG1::Register>,

    #[flop]
    pub(crate) ioc_iocfg2: CombRegister<cc2650_constants::IOC::IOCFG2::Register>,

    #[flop]
    pub(crate) ioc_iocfg3: CombRegister<cc2650_constants::IOC::IOCFG3::Register>,

    #[flop]
    pub(crate) ioc_iocfg4: CombRegister<cc2650_constants::IOC::IOCFG4::Register>,

    #[flop]
    pub(crate) ioc_iocfg5: CombRegister<cc2650_constants::IOC::IOCFG5::Register>,

    #[flop]
    pub(crate) ioc_iocfg6: CombRegister<cc2650_constants::IOC::IOCFG6::Register>,

    #[flop]
    pub(crate) ioc_iocfg7: CombRegister<cc2650_constants::IOC::IOCFG7::Register>,

    #[flop]
    pub(crate) ioc_iocfg8: CombRegister<cc2650_constants::IOC::IOCFG8::Register>,

    #[flop]
    pub(crate) ioc_iocfg9: CombRegister<cc2650_constants::IOC::IOCFG9::Register>,

    #[flop]
    pub(crate) ioc_iocfg11: CombRegister<cc2650_constants::IOC::IOCFG11::Register>,

    #[flop]
    pub(crate) ioc_iocfg13: CombRegister<cc2650_constants::IOC::IOCFG13::Register>,

    #[flop]
    pub(crate) ioc_iocfg14: CombRegister<cc2650_constants::IOC::IOCFG14::Register>,

    #[flop]
    pub(crate) ioc_iocfg20: CombRegister<cc2650_constants::IOC::IOCFG20::Register>,

    #[flop]
    pub(crate) ioc_iocfg23: CombRegister<cc2650_constants::IOC::IOCFG23::Register>,

    #[flop]
    pub(crate) ioc_iocfg25: CombRegister<cc2650_constants::IOC::IOCFG25::Register>,

    #[flop]
    pub(crate) ioc_iocfg26: CombRegister<cc2650_constants::IOC::IOCFG26::Register>,

    #[flop]
    pub(crate) ioc_iocfg27: CombRegister<cc2650_constants::IOC::IOCFG27::Register>,

    #[flop]
    pub(crate) ioc_iocfg28: CombRegister<cc2650_constants::IOC::IOCFG28::Register>,

    #[flop]
    pub(crate) ioc_iocfg29: CombRegister<cc2650_constants::IOC::IOCFG29::Register>,

    #[flop]
    pub(crate) gpt0_cfg: CombRegister<cc2650_constants::GPT0::CFG::Register>,

    #[flop]
    pub(crate) gpt0_tamr: CombRegister<cc2650_constants::GPT0::TAMR::Register>,

    #[flop]
    pub(crate) gpt0_tbmr: CombRegister<cc2650_constants::GPT0::TBMR::Register>,

    #[flop]
    pub(crate) gpt0_tbpr: CombRegister<cc2650_constants::GPT0::TBPR::Register>,

    #[flop]
    pub(crate) gpt0_ctl: CombRegister<cc2650_constants::GPT0::CTL::Register>,

    #[flop]
    pub(crate) wdt_ctl: CombRegister<cc2650_constants::WDT::CTL::Register>,

    #[flop]
    pub(crate) wdt_icr: CombRegister<cc2650_constants::WDT::ICR::Register>,

    #[flop]
    pub(crate) wdt_load: CombRegister<cc2650_constants::WDT::LOAD::Register>,

    #[flop]
    pub(crate) wdt_lock: CombRegister<cc2650_constants::WDT::LOCK::Register>,

    #[flop]
    pub(crate) aux_wuc_auxiolatch: CombRegister<cc2650_constants::AUX_WUC::AUXIOLATCH::Register>,

    #[flop]
    pub(crate) aux_sce_cpustat: CombRegister<cc2650_constants::AUX_SCE::CPUSTAT::Register>,

    #[flop]
    pub(crate) aux_aiodio0_iomode: CombRegister<cc2650_constants::AUX_AIODIO0::IOMODE::Register>,

    #[flop]
    pub(crate) aux_aiodio0_gpiodout:
        CombRegister<cc2650_constants::AUX_AIODIO0::GPIODOUT::Register>,

    #[flop]
    pub(crate) aux_aiodio0_gpiodie: CombRegister<cc2650_constants::AUX_AIODIO0::GPIODIE::Register>,

    #[flop]
    pub(crate) aux_evctl_veccfg0: CombRegister<cc2650_constants::AUX_EVCTL::VECCFG0::Register>,

    #[flop]
    pub(crate) aux_evctl_veccfg1: CombRegister<cc2650_constants::AUX_EVCTL::VECCFG1::Register>,

    #[flop]
    pub(crate) aux_sce_ctl: CombRegister<cc2650_constants::AUX_SCE::CTL::Register>,

    #[flop]
    pub(crate) aux_evctl_vecflags: CombRegister<cc2650_constants::AUX_EVCTL::VECFLAGS::Register>,

    #[flop]
    pub(crate) aux_evctl_swevset: CombRegister<cc2650_constants::AUX_EVCTL::SWEVSET::Register>,

    #[flop]
    pub(crate) aux_timer_t0ctl: CombRegister<cc2650_constants::AUX_TIMER::T0CTL::Register>,

    #[flop]
    pub(crate) aux_timer_t0target: CombRegister<cc2650_constants::AUX_TIMER::T0TARGET::Register>,

    #[flop]
    pub(crate) aux_timer_t0cfg: CombRegister<cc2650_constants::AUX_TIMER::T0CFG::Register>,

    #[flop]
    pub(crate) trng_swreset: CombRegister<cc2650_constants::TRNG::SWRESET::Register>,

    #[flop]
    pub(crate) trng_ctl: CombRegister<cc2650_constants::TRNG::CTL::Register>,

    #[flop]
    pub(crate) trng_cfg0: CombRegister<cc2650_constants::TRNG::CFG0::Register>,

    #[flop]
    pub(crate) trng_irqflagclr: CombRegister<cc2650_constants::TRNG::IRQFLAGCLR::Register>,

    #[flop]
    pub(crate) trng_irqflagstat: CombRegister<cc2650_constants::TRNG::IRQFLAGSTAT::Register>,

    #[flop]
    pub(crate) fcfg1_misc_trim: CombRegister<cc2650_constants::FCFG1::MISC_TRIM::Register>,

    #[flop]
    pub(crate) fcfg1_pwd_curr_20c: CombRegister<cc2650_constants::FCFG1::PWD_CURR_20C::Register>,

    #[flop]
    pub(crate) fcfg1_pwd_curr_35c: CombRegister<cc2650_constants::FCFG1::PWD_CURR_35C::Register>,

    #[flop]
    pub(crate) fcfg1_pwd_curr_50c: CombRegister<cc2650_constants::FCFG1::PWD_CURR_50C::Register>,

    #[flop]
    pub(crate) fcfg1_shdw_ana_trim: CombRegister<cc2650_constants::FCFG1::SHDW_ANA_TRIM::Register>,

    #[flop]
    pub(crate) uart0_fr: CombRegister<cc2650_constants::UART0::FR::Register>,

    #[flop]
    pub(crate) uart0_lcrh: CombRegister<cc2650_constants::UART0::LCRH::Register>,

    #[flop]
    pub(crate) uart0_ctl: CombRegister<cc2650_constants::UART0::CTL::Register>,

    #[flop]
    pub(crate) uart0_imsc: CombRegister<cc2650_constants::UART0::IMSC::Register>,

    #[flop]
    pub(crate) uart0_icr: CombRegister<cc2650_constants::UART0::ICR::Register>,

    #[flop]
    pub(crate) aux_smph_smph0: CombRegister<cc2650_constants::AUX_SMPH::SMPH0::Register>,

    #[flop]
    pub(crate) aux_smph_smph1: CombRegister<cc2650_constants::AUX_SMPH::SMPH1::Register>,

    #[flop]
    pub(crate) aux_smph_smph2: CombRegister<cc2650_constants::AUX_SMPH::SMPH2::Register>,

    #[flop]
    pub(crate) aux_smph_smph3: CombRegister<cc2650_constants::AUX_SMPH::SMPH3::Register>,

    #[flop]
    pub(crate) aux_smph_smph4: CombRegister<cc2650_constants::AUX_SMPH::SMPH4::Register>,

    #[flop]
    pub(crate) aux_smph_smph5: CombRegister<cc2650_constants::AUX_SMPH::SMPH5::Register>,

    #[flop]
    pub(crate) aux_smph_smph6: CombRegister<cc2650_constants::AUX_SMPH::SMPH6::Register>,

    #[flop]
    pub(crate) aux_smph_smph7: CombRegister<cc2650_constants::AUX_SMPH::SMPH7::Register>,
}

impl AutoMockComponent {
    pub fn new() -> Self {
        Self {
            fcfg1_fcfg1_revision: CombRegister::new(
                cc2650_constants::FCFG1::FCFG1_REVISION::Register::new(),
            ),
            fcfg1_icepick_device_id: CombRegister::new(
                cc2650_constants::FCFG1::ICEPICK_DEVICE_ID::Register::from(0x8b_99_a0_2f),
            ),
            fcfg1_misc_conf_1: CombRegister::new(
                cc2650_constants::FCFG1::MISC_CONF_1::Register::from(0xff_ff_ff_01),
            ),
            fcfg1_mac_15_4_0: CombRegister::new(
                cc2650_constants::FCFG1::MAC_15_4_0::Register::from(0x19_2d_82_a3),
            ),
            fcfg1_mac_15_4_1: CombRegister::new(
                cc2650_constants::FCFG1::MAC_15_4_1::Register::from(0x00_12_4b_00),
            ),
            fcfg1_user_id: CombRegister::new(cc2650_constants::FCFG1::USER_ID::Register::from(
                0x80_02_f0_00,
            )),
            ccfg_size_and_dis_flags: CombRegister::new(
                cc2650_constants::CCFG::SIZE_AND_DIS_FLAGS::Register::from(0x00_58_ff_fd),
            ),
            ccfg_mode_conf_1: CombRegister::new(
                cc2650_constants::CCFG::MODE_CONF_1::Register::from(0xff_82_00_10),
            ),
            ccfg_mode_conf: CombRegister::new(cc2650_constants::CCFG::MODE_CONF::Register::from(
                0xf3_bf_ff_3a,
            )),
            flash_cfg: CombRegister::new(cc2650_constants::FLASH::CFG::Register::from(
                0x80_00_01_25,
            )),
            flash_fpac1: CombRegister::new(cc2650_constants::FLASH::FPAC1::Register::from(
                0x02_08_20_81,
            )),
            aux_wuc_modclken0: CombRegister::new(
                cc2650_constants::AUX_WUC::MODCLKEN0::Register::new(),
            ),
            aux_wuc_modclken1: CombRegister::new(
                cc2650_constants::AUX_WUC::MODCLKEN1::Register::new(),
            ),
            aon_ioc_ioclatch: CombRegister::new(
                cc2650_constants::AON_IOC::IOCLATCH::Register::from(0x00_00_00_01),
            ),
            aon_sysctl_sleepctl: CombRegister::new(
                cc2650_constants::AON_SYSCTL::SLEEPCTL::Register::from(0x00_00_00_01),
            ),
            aon_sysctl_pwrctl: CombRegister::new(
                cc2650_constants::AON_SYSCTL::PWRCTL::Register::from(0x00_00_00_05),
            ),
            aon_sysctl_resetctl: CombRegister::new(
                cc2650_constants::AON_SYSCTL::RESETCTL::Register::new(),
            ),
            aon_batmon_bat: CombRegister::new(cc2650_constants::AON_BATMON::BAT::Register::from(
                0x00_00_03_52,
            )),
            aon_batmon_temp: CombRegister::new(cc2650_constants::AON_BATMON::TEMP::Register::from(
                0x00_00_10_40,
            )),
            fcfg1_ldo_trim: CombRegister::new(cc2650_constants::FCFG1::LDO_TRIM::Register::from(
                0xfa_f8_e0_fb,
            )),
            fcfg1_anabypass_value2: CombRegister::new(
                cc2650_constants::FCFG1::ANABYPASS_VALUE2::Register::from(0xff_ff_c3_ff),
            ),
            fcfg1_config_osc_top: CombRegister::new(
                cc2650_constants::FCFG1::CONFIG_OSC_TOP::Register::from(0xfc_00_ff_40),
            ),
            fcfg1_ampcomp_th2: CombRegister::new(
                cc2650_constants::FCFG1::AMPCOMP_TH2::Register::from(0x6b_8b_03_03),
            ),
            fcfg1_ampcomp_th1: CombRegister::new(
                cc2650_constants::FCFG1::AMPCOMP_TH1::Register::from(0xff_7b_82_8e),
            ),
            fcfg1_ampcomp_ctrl1: CombRegister::new(
                cc2650_constants::FCFG1::AMPCOMP_CTRL1::Register::from(0xff_18_3f_47),
            ),
            fcfg1_osc_conf: CombRegister::new(cc2650_constants::FCFG1::OSC_CONF::Register::from(
                0xf0_0e_00_18,
            )),
            fcfg1_misc_otp_data_1: CombRegister::new(
                cc2650_constants::FCFG1::MISC_OTP_DATA_1::Register::from(0xe0_04_03_f8),
            ),
            fcfg1_trim_cal_revision: CombRegister::new(
                cc2650_constants::FCFG1::TRIM_CAL_REVISION::Register::from(0x02_13_02_11),
            ),
            fcfg1_soc_adc_ref_trim_and_offset_ext: CombRegister::new(
                cc2650_constants::FCFG1::SOC_ADC_REF_TRIM_AND_OFFSET_EXT::Register::from(
                    0xff_00_ff_8b,
                ),
            ),
            aux_adi4_adc0: CombRegister::new(cc2650_constants::AUX_ADI4::ADC0::Register::new()),
            aon_batmon_flashpumpp0: CombRegister::new(
                cc2650_constants::AON_BATMON::FLASHPUMPP0::Register::new(),
            ),
            aux_wuc_pwroffreq: CombRegister::new(
                cc2650_constants::AUX_WUC::PWROFFREQ::Register::new(),
            ),
            aux_wuc_pwrdwnreq: CombRegister::new(
                cc2650_constants::AUX_WUC::PWRDWNREQ::Register::new(),
            ),
            aux_wuc_mcubusctl: CombRegister::new(
                cc2650_constants::AUX_WUC::MCUBUSCTL::Register::new(),
            ),
            ioc_iocfg0: CombRegister::new(cc2650_constants::IOC::IOCFG0::Register::new()),
            ioc_iocfg1: CombRegister::new(cc2650_constants::IOC::IOCFG1::Register::new()),
            ioc_iocfg2: CombRegister::new(cc2650_constants::IOC::IOCFG2::Register::new()),
            ioc_iocfg3: CombRegister::new(cc2650_constants::IOC::IOCFG3::Register::new()),
            ioc_iocfg4: CombRegister::new(cc2650_constants::IOC::IOCFG4::Register::new()),
            ioc_iocfg5: CombRegister::new(cc2650_constants::IOC::IOCFG5::Register::new()),
            ioc_iocfg6: CombRegister::new(cc2650_constants::IOC::IOCFG6::Register::new()),
            ioc_iocfg7: CombRegister::new(cc2650_constants::IOC::IOCFG7::Register::new()),
            ioc_iocfg8: CombRegister::new(cc2650_constants::IOC::IOCFG8::Register::new()),
            ioc_iocfg9: CombRegister::new(cc2650_constants::IOC::IOCFG9::Register::new()),
            ioc_iocfg11: CombRegister::new(cc2650_constants::IOC::IOCFG11::Register::new()),
            ioc_iocfg13: CombRegister::new(cc2650_constants::IOC::IOCFG13::Register::new()),
            ioc_iocfg14: CombRegister::new(cc2650_constants::IOC::IOCFG14::Register::new()),
            ioc_iocfg20: CombRegister::new(cc2650_constants::IOC::IOCFG20::Register::new()),
            ioc_iocfg23: CombRegister::new(cc2650_constants::IOC::IOCFG23::Register::new()),
            ioc_iocfg25: CombRegister::new(cc2650_constants::IOC::IOCFG25::Register::new()),
            ioc_iocfg26: CombRegister::new(cc2650_constants::IOC::IOCFG26::Register::new()),
            ioc_iocfg27: CombRegister::new(cc2650_constants::IOC::IOCFG27::Register::new()),
            ioc_iocfg28: CombRegister::new(cc2650_constants::IOC::IOCFG28::Register::new()),
            ioc_iocfg29: CombRegister::new(cc2650_constants::IOC::IOCFG29::Register::new()),
            gpt0_cfg: CombRegister::new(cc2650_constants::GPT0::CFG::Register::new()),
            gpt0_tamr: CombRegister::new(cc2650_constants::GPT0::TAMR::Register::new()),
            gpt0_tbmr: CombRegister::new(cc2650_constants::GPT0::TBMR::Register::new()),
            gpt0_tbpr: CombRegister::new(cc2650_constants::GPT0::TBPR::Register::new()),
            gpt0_ctl: CombRegister::new(cc2650_constants::GPT0::CTL::Register::new()),
            wdt_ctl: CombRegister::new(cc2650_constants::WDT::CTL::Register::new()),
            wdt_icr: CombRegister::new(cc2650_constants::WDT::ICR::Register::new()),
            wdt_load: CombRegister::new(cc2650_constants::WDT::LOAD::Register::new()),
            wdt_lock: CombRegister::new(cc2650_constants::WDT::LOCK::Register::new()),
            aux_wuc_auxiolatch: CombRegister::new(
                cc2650_constants::AUX_WUC::AUXIOLATCH::Register::new(),
            ),
            aux_sce_cpustat: CombRegister::new(cc2650_constants::AUX_SCE::CPUSTAT::Register::from(
                0x00_00_05_01,
            )),
            aux_aiodio0_iomode: CombRegister::new(
                cc2650_constants::AUX_AIODIO0::IOMODE::Register::new(),
            ),
            aux_aiodio0_gpiodout: CombRegister::new(
                cc2650_constants::AUX_AIODIO0::GPIODOUT::Register::new(),
            ),
            aux_aiodio0_gpiodie: CombRegister::new(
                cc2650_constants::AUX_AIODIO0::GPIODIE::Register::new(),
            ),
            aux_evctl_veccfg0: CombRegister::new(
                cc2650_constants::AUX_EVCTL::VECCFG0::Register::new(),
            ),
            aux_evctl_veccfg1: CombRegister::new(
                cc2650_constants::AUX_EVCTL::VECCFG1::Register::new(),
            ),
            aux_sce_ctl: CombRegister::new(cc2650_constants::AUX_SCE::CTL::Register::from(
                0x00_00_23_03,
            )),
            aux_evctl_vecflags: CombRegister::new(
                cc2650_constants::AUX_EVCTL::VECFLAGS::Register::new(),
            ),
            aux_evctl_swevset: CombRegister::new(
                cc2650_constants::AUX_EVCTL::SWEVSET::Register::new(),
            ),
            aux_timer_t0ctl: CombRegister::new(cc2650_constants::AUX_TIMER::T0CTL::Register::new()),
            aux_timer_t0target: CombRegister::new(
                cc2650_constants::AUX_TIMER::T0TARGET::Register::new(),
            ),
            aux_timer_t0cfg: CombRegister::new(cc2650_constants::AUX_TIMER::T0CFG::Register::new()),
            trng_swreset: CombRegister::new(cc2650_constants::TRNG::SWRESET::Register::new()),
            trng_ctl: CombRegister::new(cc2650_constants::TRNG::CTL::Register::new()),
            trng_cfg0: CombRegister::new(cc2650_constants::TRNG::CFG0::Register::new()),
            trng_irqflagclr: CombRegister::new(cc2650_constants::TRNG::IRQFLAGCLR::Register::new()),
            trng_irqflagstat: CombRegister::new(
                cc2650_constants::TRNG::IRQFLAGSTAT::Register::from(0x00_00_00_01),
            ),
            fcfg1_misc_trim: CombRegister::new(cc2650_constants::FCFG1::MISC_TRIM::Register::new()),
            fcfg1_pwd_curr_20c: CombRegister::new(
                cc2650_constants::FCFG1::PWD_CURR_20C::Register::from(0x08_0b_a6_08),
            ),
            fcfg1_pwd_curr_35c: CombRegister::new(
                cc2650_constants::FCFG1::PWD_CURR_35C::Register::from(0x0c_10_a5_0a),
            ),
            fcfg1_pwd_curr_50c: CombRegister::new(
                cc2650_constants::FCFG1::PWD_CURR_50C::Register::from(0x12_18_a2_0d),
            ),
            fcfg1_shdw_ana_trim: CombRegister::new(
                cc2650_constants::FCFG1::SHDW_ANA_TRIM::Register::from(0),
            ),
            uart0_fr: CombRegister::new(cc2650_constants::UART0::FR::Register::from(0)),
            uart0_lcrh: CombRegister::new(cc2650_constants::UART0::LCRH::Register::new()),
            uart0_ctl: CombRegister::new(cc2650_constants::UART0::CTL::Register::new()),
            uart0_imsc: CombRegister::new(cc2650_constants::UART0::IMSC::Register::new()),
            uart0_icr: CombRegister::new(cc2650_constants::UART0::ICR::Register::from(0)),
            aux_smph_smph0: CombRegister::new(cc2650_constants::AUX_SMPH::SMPH0::Register::from(1)),
            aux_smph_smph1: CombRegister::new(cc2650_constants::AUX_SMPH::SMPH1::Register::from(1)),
            aux_smph_smph2: CombRegister::new(cc2650_constants::AUX_SMPH::SMPH2::Register::from(1)),
            aux_smph_smph3: CombRegister::new(cc2650_constants::AUX_SMPH::SMPH3::Register::from(1)),
            aux_smph_smph4: CombRegister::new(cc2650_constants::AUX_SMPH::SMPH4::Register::from(1)),
            aux_smph_smph5: CombRegister::new(cc2650_constants::AUX_SMPH::SMPH5::Register::from(1)),
            aux_smph_smph6: CombRegister::new(cc2650_constants::AUX_SMPH::SMPH6::Register::from(1)),
            aux_smph_smph7: CombRegister::new(cc2650_constants::AUX_SMPH::SMPH7::Register::from(1)),
        }
    }
    pub fn get_data_for_address(mut this: MaybeMut<Self>, addr: Address) -> Option<[u8; 4]> {
        match addr {
            cc2650_constants::FCFG1::FCFG1_REVISION::ADDR => {
                Some(this.fcfg1_fcfg1_revision.read().to_le_bytes())
            }
            cc2650_constants::FCFG1::ICEPICK_DEVICE_ID::ADDR => {
                Some(this.fcfg1_icepick_device_id.read().to_le_bytes())
            }
            cc2650_constants::FCFG1::MISC_CONF_1::ADDR => {
                Some(this.fcfg1_misc_conf_1.read().to_le_bytes())
            }
            cc2650_constants::FCFG1::MAC_15_4_0::ADDR => {
                Some(this.fcfg1_mac_15_4_0.read().to_le_bytes())
            }
            cc2650_constants::FCFG1::MAC_15_4_1::ADDR => {
                Some(this.fcfg1_mac_15_4_1.read().to_le_bytes())
            }
            cc2650_constants::FCFG1::USER_ID::ADDR => Some(this.fcfg1_user_id.read().to_le_bytes()),
            cc2650_constants::CCFG::SIZE_AND_DIS_FLAGS::ADDR => {
                Some(this.ccfg_size_and_dis_flags.read().to_le_bytes())
            }
            cc2650_constants::CCFG::MODE_CONF_1::ADDR => {
                Some(this.ccfg_mode_conf_1.read().to_le_bytes())
            }
            cc2650_constants::CCFG::MODE_CONF::ADDR => {
                Some(this.ccfg_mode_conf.read().to_le_bytes())
            }
            cc2650_constants::FLASH::CFG::ADDR => Some(this.flash_cfg.read().to_le_bytes()),
            cc2650_constants::FLASH::FPAC1::ADDR => Some(this.flash_fpac1.read().to_le_bytes()),
            cc2650_constants::AUX_WUC::MODCLKEN0::ADDR => {
                Some(this.aux_wuc_modclken0.read().to_le_bytes())
            }
            cc2650_constants::AUX_WUC::MODCLKEN1::ADDR => {
                Some(this.aux_wuc_modclken1.read().to_le_bytes())
            }
            cc2650_constants::AON_IOC::IOCLATCH::ADDR => {
                Some(this.aon_ioc_ioclatch.read().to_le_bytes())
            }
            cc2650_constants::AON_SYSCTL::SLEEPCTL::ADDR => {
                Some(this.aon_sysctl_sleepctl.read().to_le_bytes())
            }
            cc2650_constants::AON_SYSCTL::PWRCTL::ADDR => {
                Some(this.aon_sysctl_pwrctl.read().to_le_bytes())
            }
            cc2650_constants::AON_SYSCTL::RESETCTL::ADDR => {
                Some(this.aon_sysctl_resetctl.read().to_le_bytes())
            }
            AddressExt::<0x2008_F434>::ITSELF => Some(0u32.to_le_bytes()),
            AddressExt::<0x4008_6254>::ITSELF => Some(0u32.to_le_bytes()),
            AddressExt::<0x4008_626c>::ITSELF => Some(0u32.to_le_bytes()),
            cc2650_constants::AON_BATMON::BAT::ADDR => {
                Some(this.aon_batmon_bat.read().to_le_bytes())
            }
            cc2650_constants::AON_BATMON::TEMP::ADDR => {
                Some(this.aon_batmon_temp.read().to_le_bytes())
            }
            AddressExt::<0x400c_a258>::ITSELF => Some(0u32.to_le_bytes()),
            AddressExt::<0x400c_a040>::ITSELF => Some(0u32.to_le_bytes()),
            AddressExt::<0x400c_a080>::ITSELF => Some(0u32.to_le_bytes()),
            AddressExt::<0x400c_a108>::ITSELF => Some(0u32.to_le_bytes()),
            AddressExt::<0x400c_a140>::ITSELF => Some(0u32.to_le_bytes()),
            AddressExt::<0x400c_a148>::ITSELF => Some(0u32.to_le_bytes()),
            AddressExt::<0x400c_a14c>::ITSELF => Some(0u32.to_le_bytes()),
            AddressExt::<0x400c_a1dc>::ITSELF => Some(0u32.to_le_bytes()),
            AddressExt::<0x400c_a200>::ITSELF => Some(0u32.to_le_bytes()),
            AddressExt::<0x400c_a204>::ITSELF => Some(0u32.to_le_bytes()),
            AddressExt::<0x400c_b070>::ITSELF => Some(0u32.to_le_bytes()),
            cc2650_constants::FCFG1::LDO_TRIM::ADDR => {
                Some(this.fcfg1_ldo_trim.read().to_le_bytes())
            }
            cc2650_constants::FCFG1::ANABYPASS_VALUE2::ADDR => {
                Some(this.fcfg1_anabypass_value2.read().to_le_bytes())
            }
            cc2650_constants::FCFG1::CONFIG_OSC_TOP::ADDR => {
                Some(this.fcfg1_config_osc_top.read().to_le_bytes())
            }
            cc2650_constants::FCFG1::AMPCOMP_TH2::ADDR => {
                Some(this.fcfg1_ampcomp_th2.read().to_le_bytes())
            }
            cc2650_constants::FCFG1::AMPCOMP_TH1::ADDR => {
                Some(this.fcfg1_ampcomp_th1.read().to_le_bytes())
            }
            cc2650_constants::FCFG1::AMPCOMP_CTRL1::ADDR => {
                Some(this.fcfg1_ampcomp_ctrl1.read().to_le_bytes())
            }
            cc2650_constants::FCFG1::OSC_CONF::ADDR => {
                Some(this.fcfg1_osc_conf.read().to_le_bytes())
            }
            cc2650_constants::FCFG1::MISC_OTP_DATA_1::ADDR => {
                Some(this.fcfg1_misc_otp_data_1.read().to_le_bytes())
            }
            cc2650_constants::FCFG1::TRIM_CAL_REVISION::ADDR => {
                Some(this.fcfg1_trim_cal_revision.read().to_le_bytes())
            }
            cc2650_constants::FCFG1::SOC_ADC_REF_TRIM_AND_OFFSET_EXT::ADDR => Some(
                this.fcfg1_soc_adc_ref_trim_and_offset_ext
                    .read()
                    .to_le_bytes(),
            ),
            cc2650_constants::AUX_ADI4::ADC0::ADDR => Some(this.aux_adi4_adc0.read().to_le_bytes()),
            cc2650_constants::AON_BATMON::FLASHPUMPP0::ADDR => {
                Some(this.aon_batmon_flashpumpp0.read().to_le_bytes())
            }
            cc2650_constants::AUX_WUC::PWROFFREQ::ADDR => {
                Some(this.aux_wuc_pwroffreq.read().to_le_bytes())
            }
            cc2650_constants::AUX_WUC::PWRDWNREQ::ADDR => {
                Some(this.aux_wuc_pwrdwnreq.read().to_le_bytes())
            }
            cc2650_constants::AUX_WUC::MCUBUSCTL::ADDR => {
                Some(this.aux_wuc_mcubusctl.read().to_le_bytes())
            }
            AddressExt::<0x4002_20c4>::ITSELF => Some(0u32.to_le_bytes()),
            AddressExt::<0x4002_20c8>::ITSELF => Some(0u32.to_le_bytes()),
            AddressExt::<0x4002_20cc>::ITSELF => Some(0u32.to_le_bytes()),
            AddressExt::<0x4002_20e4>::ITSELF => Some(0u32.to_le_bytes()),
            AddressExt::<0x4002_20e8>::ITSELF => Some(0u32.to_le_bytes()),
            cc2650_constants::IOC::IOCFG0::ADDR => Some(this.ioc_iocfg0.read().to_le_bytes()),
            cc2650_constants::IOC::IOCFG1::ADDR => Some(this.ioc_iocfg1.read().to_le_bytes()),
            cc2650_constants::IOC::IOCFG2::ADDR => Some(this.ioc_iocfg2.read().to_le_bytes()),
            cc2650_constants::IOC::IOCFG3::ADDR => Some(this.ioc_iocfg3.read().to_le_bytes()),
            cc2650_constants::IOC::IOCFG4::ADDR => Some(this.ioc_iocfg4.read().to_le_bytes()),
            cc2650_constants::IOC::IOCFG5::ADDR => Some(this.ioc_iocfg5.read().to_le_bytes()),
            cc2650_constants::IOC::IOCFG6::ADDR => Some(this.ioc_iocfg6.read().to_le_bytes()),
            cc2650_constants::IOC::IOCFG7::ADDR => Some(this.ioc_iocfg7.read().to_le_bytes()),
            cc2650_constants::IOC::IOCFG8::ADDR => Some(this.ioc_iocfg8.read().to_le_bytes()),
            cc2650_constants::IOC::IOCFG9::ADDR => Some(this.ioc_iocfg9.read().to_le_bytes()),
            cc2650_constants::IOC::IOCFG11::ADDR => Some(this.ioc_iocfg11.read().to_le_bytes()),
            cc2650_constants::IOC::IOCFG13::ADDR => Some(this.ioc_iocfg13.read().to_le_bytes()),
            cc2650_constants::IOC::IOCFG14::ADDR => Some(this.ioc_iocfg14.read().to_le_bytes()),
            cc2650_constants::IOC::IOCFG20::ADDR => Some(this.ioc_iocfg20.read().to_le_bytes()),
            cc2650_constants::IOC::IOCFG23::ADDR => Some(this.ioc_iocfg23.read().to_le_bytes()),
            cc2650_constants::IOC::IOCFG25::ADDR => Some(this.ioc_iocfg25.read().to_le_bytes()),
            cc2650_constants::IOC::IOCFG26::ADDR => Some(this.ioc_iocfg26.read().to_le_bytes()),
            cc2650_constants::IOC::IOCFG27::ADDR => Some(this.ioc_iocfg27.read().to_le_bytes()),
            cc2650_constants::IOC::IOCFG28::ADDR => Some(this.ioc_iocfg28.read().to_le_bytes()),
            cc2650_constants::IOC::IOCFG29::ADDR => Some(this.ioc_iocfg29.read().to_le_bytes()),
            cc2650_constants::GPT0::CFG::ADDR => Some(this.gpt0_cfg.read().to_le_bytes()),
            cc2650_constants::GPT0::TAMR::ADDR => Some(this.gpt0_tamr.read().to_le_bytes()),
            cc2650_constants::GPT0::TBMR::ADDR => Some(this.gpt0_tbmr.read().to_le_bytes()),
            cc2650_constants::GPT0::TBPR::ADDR => Some(this.gpt0_tbpr.read().to_le_bytes()),
            cc2650_constants::GPT0::CTL::ADDR => Some(this.gpt0_ctl.read().to_le_bytes()),
            cc2650_constants::WDT::CTL::ADDR => Some(this.wdt_ctl.read().to_le_bytes()),
            cc2650_constants::WDT::ICR::ADDR => Some(this.wdt_icr.read().to_le_bytes()),
            cc2650_constants::WDT::LOAD::ADDR => Some(this.wdt_load.read().to_le_bytes()),
            cc2650_constants::WDT::LOCK::ADDR => Some(this.wdt_lock.read().to_le_bytes()),
            cc2650_constants::AUX_WUC::AUXIOLATCH::ADDR => {
                Some(this.aux_wuc_auxiolatch.read().to_le_bytes())
            }
            cc2650_constants::AUX_SCE::CPUSTAT::ADDR => {
                Some(this.aux_sce_cpustat.read().to_le_bytes())
            }
            cc2650_constants::AUX_AIODIO0::IOMODE::ADDR => {
                Some(this.aux_aiodio0_iomode.read().to_le_bytes())
            }
            cc2650_constants::AUX_AIODIO0::GPIODOUT::ADDR => {
                Some(this.aux_aiodio0_gpiodout.read().to_le_bytes())
            }
            cc2650_constants::AUX_AIODIO0::GPIODIE::ADDR => {
                Some(this.aux_aiodio0_gpiodie.read().to_le_bytes())
            }
            cc2650_constants::AUX_EVCTL::VECCFG0::ADDR => {
                Some(this.aux_evctl_veccfg0.read().to_le_bytes())
            }
            cc2650_constants::AUX_EVCTL::VECCFG1::ADDR => {
                Some(this.aux_evctl_veccfg1.read().to_le_bytes())
            }
            cc2650_constants::AUX_SCE::CTL::ADDR => Some(this.aux_sce_ctl.read().to_le_bytes()),
            cc2650_constants::AUX_EVCTL::VECFLAGS::ADDR => {
                Some(this.aux_evctl_vecflags.read().to_le_bytes())
            }
            cc2650_constants::AUX_EVCTL::SWEVSET::ADDR => {
                Some(this.aux_evctl_swevset.read().to_le_bytes())
            }
            cc2650_constants::AUX_TIMER::T0CTL::ADDR => {
                Some(this.aux_timer_t0ctl.read().to_le_bytes())
            }
            cc2650_constants::AUX_TIMER::T0TARGET::ADDR => {
                Some(this.aux_timer_t0target.read().to_le_bytes())
            }
            cc2650_constants::AUX_TIMER::T0CFG::ADDR => {
                Some(this.aux_timer_t0cfg.read().to_le_bytes())
            }
            cc2650_constants::TRNG::SWRESET::ADDR => Some(this.trng_swreset.read().to_le_bytes()),
            cc2650_constants::TRNG::CTL::ADDR => Some(this.trng_ctl.read().to_le_bytes()),
            cc2650_constants::TRNG::CFG0::ADDR => Some(this.trng_cfg0.read().to_le_bytes()),
            cc2650_constants::TRNG::IRQFLAGCLR::ADDR => {
                Some(this.trng_irqflagclr.read().to_le_bytes())
            }
            cc2650_constants::TRNG::IRQFLAGSTAT::ADDR => {
                Some(this.trng_irqflagstat.read().to_le_bytes())
            }
            cc2650_constants::FCFG1::MISC_TRIM::ADDR => {
                Some(this.fcfg1_misc_trim.read().to_le_bytes())
            }
            cc2650_constants::FCFG1::PWD_CURR_20C::ADDR => {
                Some(this.fcfg1_pwd_curr_20c.read().to_le_bytes())
            }
            cc2650_constants::FCFG1::PWD_CURR_35C::ADDR => {
                Some(this.fcfg1_pwd_curr_35c.read().to_le_bytes())
            }
            cc2650_constants::FCFG1::PWD_CURR_50C::ADDR => {
                Some(this.fcfg1_pwd_curr_50c.read().to_le_bytes())
            }
            cc2650_constants::FCFG1::SHDW_ANA_TRIM::ADDR => {
                Some(this.fcfg1_shdw_ana_trim.read().to_le_bytes())
            }
            cc2650_constants::UART0::FR::ADDR => Some(this.uart0_fr.read().to_le_bytes()),
            cc2650_constants::UART0::LCRH::ADDR => Some(this.uart0_lcrh.read().to_le_bytes()),
            cc2650_constants::UART0::CTL::ADDR => Some(this.uart0_ctl.read().to_le_bytes()),
            cc2650_constants::UART0::IMSC::ADDR => Some(this.uart0_imsc.read().to_le_bytes()),
            cc2650_constants::UART0::ICR::ADDR => Some(this.uart0_icr.read().to_le_bytes()),
            cc2650_constants::AUX_SMPH::SMPH0::ADDR => {
                let available = this.aux_smph_smph0.bitfields().STAT() == 1;
                let value = if available {
                    if let Some(this) = this.get_mut() {
                        this.aux_smph_smph0.set_next_mutated_reg(0u32);
                    }
                    1u32
                } else {
                    0u32
                }
                .to_le_bytes();
                Some(value)
            }
            cc2650_constants::AUX_SMPH::SMPH1::ADDR => {
                let available = this.aux_smph_smph1.bitfields().STAT() == 1;
                let value = if available {
                    if let Some(this) = this.get_mut() {
                        this.aux_smph_smph1.set_next_mutated_reg(0u32);
                    }
                    1u32
                } else {
                    0u32
                }
                .to_le_bytes();
                Some(value)
            }
            cc2650_constants::AUX_SMPH::SMPH2::ADDR => {
                let available = this.aux_smph_smph2.bitfields().STAT() == 1;
                let value = if available {
                    if let Some(this) = this.get_mut() {
                        this.aux_smph_smph2.set_next_mutated_reg(0u32);
                    }
                    1u32
                } else {
                    0u32
                }
                .to_le_bytes();
                Some(value)
            }
            cc2650_constants::AUX_SMPH::SMPH3::ADDR => {
                let available = this.aux_smph_smph3.bitfields().STAT() == 1;
                let value = if available {
                    if let Some(this) = this.get_mut() {
                        this.aux_smph_smph3.set_next_mutated_reg(0u32);
                    }
                    1u32
                } else {
                    0u32
                }
                .to_le_bytes();
                Some(value)
            }
            cc2650_constants::AUX_SMPH::SMPH4::ADDR => {
                let available = this.aux_smph_smph4.bitfields().STAT() == 1;
                let value = if available {
                    if let Some(this) = this.get_mut() {
                        this.aux_smph_smph4.set_next_mutated_reg(0u32);
                    }
                    1u32
                } else {
                    0u32
                }
                .to_le_bytes();
                Some(value)
            }
            cc2650_constants::AUX_SMPH::SMPH5::ADDR => {
                let available = this.aux_smph_smph5.bitfields().STAT() == 1;
                let value = if available {
                    if let Some(this) = this.get_mut() {
                        this.aux_smph_smph5.set_next_mutated_reg(0u32);
                    }
                    1u32
                } else {
                    0u32
                }
                .to_le_bytes();
                Some(value)
            }
            cc2650_constants::AUX_SMPH::SMPH6::ADDR => {
                let available = this.aux_smph_smph6.bitfields().STAT() == 1;
                let value = if available {
                    if let Some(this) = this.get_mut() {
                        this.aux_smph_smph6.set_next_mutated_reg(0u32);
                    }
                    1u32
                } else {
                    0u32
                }
                .to_le_bytes();
                Some(value)
            }
            cc2650_constants::AUX_SMPH::SMPH7::ADDR => {
                let available = this.aux_smph_smph7.bitfields().STAT() == 1;
                let value = if available {
                    if let Some(this) = this.get_mut() {
                        this.aux_smph_smph7.set_next_mutated_reg(0u32);
                    }
                    1u32
                } else {
                    0u32
                }
                .to_le_bytes();
                Some(value)
            }

            _ => None,
        }
    }
    pub fn set_data_for_address(&mut self, addr: Address, data: [u8; 4]) -> Option<()> {
        match addr {
            cc2650_constants::FCFG1::FCFG1_REVISION::ADDR => {
                self.fcfg1_fcfg1_revision
                    .set_next_mutated_reg(u32::from_le_bytes(data));
                Some(())
            }
            cc2650_constants::FCFG1::ICEPICK_DEVICE_ID::ADDR => {
                self.fcfg1_icepick_device_id
                    .set_next_mutated_reg(u32::from_le_bytes(data));
                Some(())
            }
            cc2650_constants::FCFG1::MISC_CONF_1::ADDR => {
                self.fcfg1_misc_conf_1
                    .set_next_mutated_reg(u32::from_le_bytes(data));
                Some(())
            }
            cc2650_constants::FCFG1::MAC_15_4_0::ADDR => {
                self.fcfg1_mac_15_4_0
                    .set_next_mutated_reg(u32::from_le_bytes(data));
                Some(())
            }
            cc2650_constants::FCFG1::MAC_15_4_1::ADDR => {
                self.fcfg1_mac_15_4_1
                    .set_next_mutated_reg(u32::from_le_bytes(data));
                Some(())
            }
            cc2650_constants::FCFG1::USER_ID::ADDR => {
                self.fcfg1_user_id
                    .set_next_mutated_reg(u32::from_le_bytes(data));
                Some(())
            }
            cc2650_constants::CCFG::SIZE_AND_DIS_FLAGS::ADDR => {
                self.ccfg_size_and_dis_flags
                    .set_next_mutated_reg(u32::from_le_bytes(data));
                Some(())
            }
            cc2650_constants::CCFG::MODE_CONF_1::ADDR => {
                self.ccfg_mode_conf_1
                    .set_next_mutated_reg(u32::from_le_bytes(data));
                Some(())
            }
            cc2650_constants::CCFG::MODE_CONF::ADDR => {
                self.ccfg_mode_conf
                    .set_next_mutated_reg(u32::from_le_bytes(data));
                Some(())
            }
            cc2650_constants::FLASH::CFG::ADDR => {
                self.flash_cfg
                    .set_next_mutated_reg(u32::from_le_bytes(data));
                Some(())
            }
            cc2650_constants::FLASH::FPAC1::ADDR => {
                self.flash_fpac1
                    .set_next_mutated_reg(u32::from_le_bytes(data));
                Some(())
            }
            cc2650_constants::AUX_WUC::MODCLKEN0::ADDR => {
                self.aux_wuc_modclken0
                    .set_next_mutated_reg(u32::from_le_bytes(data));
                Some(())
            }
            cc2650_constants::AUX_WUC::MODCLKEN1::ADDR => {
                self.aux_wuc_modclken1
                    .set_next_mutated_reg(u32::from_le_bytes(data));
                Some(())
            }
            cc2650_constants::AON_IOC::IOCLATCH::ADDR => {
                self.aon_ioc_ioclatch
                    .set_next_mutated_reg(u32::from_le_bytes(data));
                Some(())
            }
            cc2650_constants::AON_SYSCTL::SLEEPCTL::ADDR => {
                self.aon_sysctl_sleepctl
                    .set_next_mutated_reg(u32::from_le_bytes(data));
                Some(())
            }
            cc2650_constants::AON_SYSCTL::PWRCTL::ADDR => {
                self.aon_sysctl_pwrctl
                    .set_next_mutated_reg(u32::from_le_bytes(data));
                Some(())
            }
            cc2650_constants::AON_SYSCTL::RESETCTL::ADDR => {
                self.aon_sysctl_resetctl
                    .set_next_mutated_reg(u32::from_le_bytes(data));
                Some(())
            }
            AddressExt::<0x2008_F434>::ITSELF => Some(()),
            AddressExt::<0x4008_6254>::ITSELF => Some(()),
            AddressExt::<0x4008_626c>::ITSELF => Some(()),
            cc2650_constants::AON_BATMON::BAT::ADDR => {
                self.aon_batmon_bat
                    .set_next_mutated_reg(u32::from_le_bytes(data));
                Some(())
            }
            cc2650_constants::AON_BATMON::TEMP::ADDR => {
                self.aon_batmon_temp
                    .set_next_mutated_reg(u32::from_le_bytes(data));
                Some(())
            }
            AddressExt::<0x400c_a258>::ITSELF => Some(()),
            AddressExt::<0x400c_a040>::ITSELF => Some(()),
            AddressExt::<0x400c_a080>::ITSELF => Some(()),
            AddressExt::<0x400c_a108>::ITSELF => Some(()),
            AddressExt::<0x400c_a140>::ITSELF => Some(()),
            AddressExt::<0x400c_a148>::ITSELF => Some(()),
            AddressExt::<0x400c_a14c>::ITSELF => Some(()),
            AddressExt::<0x400c_a1dc>::ITSELF => Some(()),
            AddressExt::<0x400c_a200>::ITSELF => Some(()),
            AddressExt::<0x400c_a204>::ITSELF => Some(()),
            AddressExt::<0x400c_b070>::ITSELF => Some(()),
            cc2650_constants::FCFG1::LDO_TRIM::ADDR => {
                self.fcfg1_ldo_trim
                    .set_next_mutated_reg(u32::from_le_bytes(data));
                Some(())
            }
            cc2650_constants::FCFG1::ANABYPASS_VALUE2::ADDR => {
                self.fcfg1_anabypass_value2
                    .set_next_mutated_reg(u32::from_le_bytes(data));
                Some(())
            }
            cc2650_constants::FCFG1::CONFIG_OSC_TOP::ADDR => {
                self.fcfg1_config_osc_top
                    .set_next_mutated_reg(u32::from_le_bytes(data));
                Some(())
            }
            cc2650_constants::FCFG1::AMPCOMP_TH2::ADDR => {
                self.fcfg1_ampcomp_th2
                    .set_next_mutated_reg(u32::from_le_bytes(data));
                Some(())
            }
            cc2650_constants::FCFG1::AMPCOMP_TH1::ADDR => {
                self.fcfg1_ampcomp_th1
                    .set_next_mutated_reg(u32::from_le_bytes(data));
                Some(())
            }
            cc2650_constants::FCFG1::AMPCOMP_CTRL1::ADDR => {
                self.fcfg1_ampcomp_ctrl1
                    .set_next_mutated_reg(u32::from_le_bytes(data));
                Some(())
            }
            cc2650_constants::FCFG1::OSC_CONF::ADDR => {
                self.fcfg1_osc_conf
                    .set_next_mutated_reg(u32::from_le_bytes(data));
                Some(())
            }
            cc2650_constants::FCFG1::MISC_OTP_DATA_1::ADDR => {
                self.fcfg1_misc_otp_data_1
                    .set_next_mutated_reg(u32::from_le_bytes(data));
                Some(())
            }
            cc2650_constants::FCFG1::TRIM_CAL_REVISION::ADDR => {
                self.fcfg1_trim_cal_revision
                    .set_next_mutated_reg(u32::from_le_bytes(data));
                Some(())
            }
            cc2650_constants::FCFG1::SOC_ADC_REF_TRIM_AND_OFFSET_EXT::ADDR => {
                self.fcfg1_soc_adc_ref_trim_and_offset_ext
                    .set_next_mutated_reg(u32::from_le_bytes(data));
                Some(())
            }
            cc2650_constants::AUX_ADI4::ADC0::ADDR => {
                self.aux_adi4_adc0
                    .set_next_mutated_reg(u32::from_le_bytes(data));
                Some(())
            }
            cc2650_constants::AON_BATMON::FLASHPUMPP0::ADDR => {
                self.aon_batmon_flashpumpp0
                    .set_next_mutated_reg(u32::from_le_bytes(data));
                Some(())
            }
            cc2650_constants::AUX_WUC::PWROFFREQ::ADDR => {
                self.aux_wuc_pwroffreq
                    .set_next_mutated_reg(u32::from_le_bytes(data));
                Some(())
            }
            cc2650_constants::AUX_WUC::PWRDWNREQ::ADDR => {
                self.aux_wuc_pwrdwnreq
                    .set_next_mutated_reg(u32::from_le_bytes(data));
                Some(())
            }
            cc2650_constants::AUX_WUC::MCUBUSCTL::ADDR => {
                self.aux_wuc_mcubusctl
                    .set_next_mutated_reg(u32::from_le_bytes(data));
                Some(())
            }
            AddressExt::<0x4002_20c4>::ITSELF => Some(()),
            AddressExt::<0x4002_20c8>::ITSELF => Some(()),
            AddressExt::<0x4002_20cc>::ITSELF => Some(()),
            AddressExt::<0x4002_20e4>::ITSELF => Some(()),
            AddressExt::<0x4002_20e8>::ITSELF => Some(()),
            cc2650_constants::IOC::IOCFG0::ADDR => {
                self.ioc_iocfg0
                    .set_next_mutated_reg(u32::from_le_bytes(data));
                Some(())
            }
            cc2650_constants::IOC::IOCFG1::ADDR => {
                self.ioc_iocfg1
                    .set_next_mutated_reg(u32::from_le_bytes(data));
                Some(())
            }
            cc2650_constants::IOC::IOCFG2::ADDR => {
                self.ioc_iocfg2
                    .set_next_mutated_reg(u32::from_le_bytes(data));
                Some(())
            }
            cc2650_constants::IOC::IOCFG3::ADDR => {
                self.ioc_iocfg3
                    .set_next_mutated_reg(u32::from_le_bytes(data));
                Some(())
            }
            cc2650_constants::IOC::IOCFG4::ADDR => {
                self.ioc_iocfg4
                    .set_next_mutated_reg(u32::from_le_bytes(data));
                Some(())
            }
            cc2650_constants::IOC::IOCFG5::ADDR => {
                self.ioc_iocfg5
                    .set_next_mutated_reg(u32::from_le_bytes(data));
                Some(())
            }
            cc2650_constants::IOC::IOCFG6::ADDR => {
                self.ioc_iocfg6
                    .set_next_mutated_reg(u32::from_le_bytes(data));
                Some(())
            }
            cc2650_constants::IOC::IOCFG7::ADDR => {
                self.ioc_iocfg7
                    .set_next_mutated_reg(u32::from_le_bytes(data));
                Some(())
            }
            cc2650_constants::IOC::IOCFG8::ADDR => {
                self.ioc_iocfg8
                    .set_next_mutated_reg(u32::from_le_bytes(data));
                Some(())
            }
            cc2650_constants::IOC::IOCFG9::ADDR => {
                self.ioc_iocfg9
                    .set_next_mutated_reg(u32::from_le_bytes(data));
                Some(())
            }
            cc2650_constants::IOC::IOCFG11::ADDR => {
                self.ioc_iocfg11
                    .set_next_mutated_reg(u32::from_le_bytes(data));
                Some(())
            }
            cc2650_constants::IOC::IOCFG13::ADDR => {
                self.ioc_iocfg13
                    .set_next_mutated_reg(u32::from_le_bytes(data));
                Some(())
            }
            cc2650_constants::IOC::IOCFG14::ADDR => {
                self.ioc_iocfg14
                    .set_next_mutated_reg(u32::from_le_bytes(data));
                Some(())
            }
            cc2650_constants::IOC::IOCFG20::ADDR => {
                self.ioc_iocfg20
                    .set_next_mutated_reg(u32::from_le_bytes(data));
                Some(())
            }
            cc2650_constants::IOC::IOCFG23::ADDR => {
                self.ioc_iocfg23
                    .set_next_mutated_reg(u32::from_le_bytes(data));
                Some(())
            }
            cc2650_constants::IOC::IOCFG25::ADDR => {
                self.ioc_iocfg25
                    .set_next_mutated_reg(u32::from_le_bytes(data));
                Some(())
            }
            cc2650_constants::IOC::IOCFG26::ADDR => {
                self.ioc_iocfg26
                    .set_next_mutated_reg(u32::from_le_bytes(data));
                Some(())
            }
            cc2650_constants::IOC::IOCFG27::ADDR => {
                self.ioc_iocfg27
                    .set_next_mutated_reg(u32::from_le_bytes(data));
                Some(())
            }
            cc2650_constants::IOC::IOCFG28::ADDR => {
                self.ioc_iocfg28
                    .set_next_mutated_reg(u32::from_le_bytes(data));
                Some(())
            }
            cc2650_constants::IOC::IOCFG29::ADDR => {
                self.ioc_iocfg29
                    .set_next_mutated_reg(u32::from_le_bytes(data));
                Some(())
            }
            cc2650_constants::GPT0::CFG::ADDR => {
                self.gpt0_cfg.set_next_mutated_reg(u32::from_le_bytes(data));
                Some(())
            }
            cc2650_constants::GPT0::TAMR::ADDR => {
                self.gpt0_tamr
                    .set_next_mutated_reg(u32::from_le_bytes(data));
                Some(())
            }
            cc2650_constants::GPT0::TBMR::ADDR => {
                self.gpt0_tbmr
                    .set_next_mutated_reg(u32::from_le_bytes(data));
                Some(())
            }
            cc2650_constants::GPT0::TBPR::ADDR => {
                self.gpt0_tbpr
                    .set_next_mutated_reg(u32::from_le_bytes(data));
                Some(())
            }
            cc2650_constants::GPT0::CTL::ADDR => {
                self.gpt0_ctl.set_next_mutated_reg(u32::from_le_bytes(data));
                Some(())
            }
            cc2650_constants::WDT::CTL::ADDR => {
                self.wdt_ctl.set_next_mutated_reg(u32::from_le_bytes(data));
                Some(())
            }
            cc2650_constants::WDT::ICR::ADDR => {
                self.wdt_icr.set_next_mutated_reg(u32::from_le_bytes(data));
                Some(())
            }
            cc2650_constants::WDT::LOAD::ADDR => {
                self.wdt_load.set_next_mutated_reg(u32::from_le_bytes(data));
                Some(())
            }
            cc2650_constants::WDT::LOCK::ADDR => {
                self.wdt_lock.set_next_mutated_reg(u32::from_le_bytes(data));
                Some(())
            }
            cc2650_constants::AUX_WUC::AUXIOLATCH::ADDR => {
                self.aux_wuc_auxiolatch
                    .set_next_mutated_reg(u32::from_le_bytes(data));
                Some(())
            }
            cc2650_constants::AUX_SCE::CPUSTAT::ADDR => {
                self.aux_sce_cpustat
                    .set_next_mutated_reg(u32::from_le_bytes(data));
                Some(())
            }
            cc2650_constants::AUX_AIODIO0::IOMODE::ADDR => {
                self.aux_aiodio0_iomode
                    .set_next_mutated_reg(u32::from_le_bytes(data));
                Some(())
            }
            cc2650_constants::AUX_AIODIO0::GPIODOUT::ADDR => {
                self.aux_aiodio0_gpiodout
                    .set_next_mutated_reg(u32::from_le_bytes(data));
                Some(())
            }
            cc2650_constants::AUX_AIODIO0::GPIODIE::ADDR => {
                self.aux_aiodio0_gpiodie
                    .set_next_mutated_reg(u32::from_le_bytes(data));
                Some(())
            }
            cc2650_constants::AUX_EVCTL::VECCFG0::ADDR => {
                self.aux_evctl_veccfg0
                    .set_next_mutated_reg(u32::from_le_bytes(data));
                Some(())
            }
            cc2650_constants::AUX_EVCTL::VECCFG1::ADDR => {
                self.aux_evctl_veccfg1
                    .set_next_mutated_reg(u32::from_le_bytes(data));
                Some(())
            }
            cc2650_constants::AUX_SCE::CTL::ADDR => {
                self.aux_sce_ctl
                    .set_next_mutated_reg(u32::from_le_bytes(data));
                Some(())
            }
            cc2650_constants::AUX_EVCTL::VECFLAGS::ADDR => {
                self.aux_evctl_vecflags
                    .set_next_mutated_reg(u32::from_le_bytes(data));
                Some(())
            }
            cc2650_constants::AUX_EVCTL::SWEVSET::ADDR => {
                self.aux_evctl_swevset
                    .set_next_mutated_reg(u32::from_le_bytes(data));
                Some(())
            }
            cc2650_constants::AUX_TIMER::T0CTL::ADDR => {
                self.aux_timer_t0ctl
                    .set_next_mutated_reg(u32::from_le_bytes(data));
                Some(())
            }
            cc2650_constants::AUX_TIMER::T0TARGET::ADDR => {
                self.aux_timer_t0target
                    .set_next_mutated_reg(u32::from_le_bytes(data));
                Some(())
            }
            cc2650_constants::AUX_TIMER::T0CFG::ADDR => {
                self.aux_timer_t0cfg
                    .set_next_mutated_reg(u32::from_le_bytes(data));
                Some(())
            }
            cc2650_constants::TRNG::SWRESET::ADDR => {
                self.trng_swreset
                    .set_next_mutated_reg(u32::from_le_bytes(data));
                Some(())
            }
            cc2650_constants::TRNG::CTL::ADDR => {
                self.trng_ctl.set_next_mutated_reg(u32::from_le_bytes(data));
                Some(())
            }
            cc2650_constants::TRNG::CFG0::ADDR => {
                self.trng_cfg0
                    .set_next_mutated_reg(u32::from_le_bytes(data));
                Some(())
            }
            cc2650_constants::TRNG::IRQFLAGCLR::ADDR => {
                self.trng_irqflagclr
                    .set_next_mutated_reg(u32::from_le_bytes(data));
                Some(())
            }
            cc2650_constants::TRNG::IRQFLAGSTAT::ADDR => {
                self.trng_irqflagstat
                    .set_next_mutated_reg(u32::from_le_bytes(data));
                Some(())
            }
            cc2650_constants::FCFG1::MISC_TRIM::ADDR => {
                self.fcfg1_misc_trim
                    .set_next_mutated_reg(u32::from_le_bytes(data));
                Some(())
            }
            cc2650_constants::FCFG1::PWD_CURR_20C::ADDR => {
                self.fcfg1_pwd_curr_20c
                    .set_next_mutated_reg(u32::from_le_bytes(data));
                Some(())
            }
            cc2650_constants::FCFG1::PWD_CURR_35C::ADDR => {
                self.fcfg1_pwd_curr_35c
                    .set_next_mutated_reg(u32::from_le_bytes(data));
                Some(())
            }
            cc2650_constants::FCFG1::PWD_CURR_50C::ADDR => {
                self.fcfg1_pwd_curr_50c
                    .set_next_mutated_reg(u32::from_le_bytes(data));
                Some(())
            }
            cc2650_constants::FCFG1::SHDW_ANA_TRIM::ADDR => {
                self.fcfg1_shdw_ana_trim
                    .set_next_mutated_reg(u32::from_le_bytes(data));
                Some(())
            }
            cc2650_constants::UART0::FR::ADDR => {
                self.uart0_fr.set_next_mutated_reg(u32::from_le_bytes(data));
                Some(())
            }
            cc2650_constants::UART0::LCRH::ADDR => {
                self.uart0_lcrh
                    .set_next_mutated_reg(u32::from_le_bytes(data));
                Some(())
            }
            cc2650_constants::UART0::CTL::ADDR => {
                self.uart0_ctl
                    .set_next_mutated_reg(u32::from_le_bytes(data));
                Some(())
            }
            cc2650_constants::UART0::IMSC::ADDR => {
                self.uart0_imsc
                    .set_next_mutated_reg(u32::from_le_bytes(data));
                Some(())
            }
            cc2650_constants::UART0::ICR::ADDR => {
                self.uart0_icr
                    .set_next_mutated_reg(u32::from_le_bytes(data));
                Some(())
            }
            cc2650_constants::AUX_SMPH::SMPH0::ADDR => {
                self.aux_smph_smph0
                    .set_next_mutated_reg(u32::from_le_bytes(data));
                Some(())
            }
            cc2650_constants::AUX_SMPH::SMPH1::ADDR => {
                self.aux_smph_smph1
                    .set_next_mutated_reg(u32::from_le_bytes(data));
                Some(())
            }
            cc2650_constants::AUX_SMPH::SMPH2::ADDR => {
                self.aux_smph_smph2
                    .set_next_mutated_reg(u32::from_le_bytes(data));
                Some(())
            }
            cc2650_constants::AUX_SMPH::SMPH3::ADDR => {
                self.aux_smph_smph3
                    .set_next_mutated_reg(u32::from_le_bytes(data));
                Some(())
            }
            cc2650_constants::AUX_SMPH::SMPH4::ADDR => {
                self.aux_smph_smph4
                    .set_next_mutated_reg(u32::from_le_bytes(data));
                Some(())
            }
            cc2650_constants::AUX_SMPH::SMPH5::ADDR => {
                self.aux_smph_smph5
                    .set_next_mutated_reg(u32::from_le_bytes(data));
                Some(())
            }
            cc2650_constants::AUX_SMPH::SMPH6::ADDR => {
                self.aux_smph_smph6
                    .set_next_mutated_reg(u32::from_le_bytes(data));
                Some(())
            }
            cc2650_constants::AUX_SMPH::SMPH7::ADDR => {
                self.aux_smph_smph7
                    .set_next_mutated_reg(u32::from_le_bytes(data));
                Some(())
            }
            _ => None,
        }
    }
}
